### PR TITLE
Math

### PR DESCRIPTION
**Pull request by JEAlfonsoP**
Hi. I defined a math folder in order to include all math theory - concepts in it.
I would also suggest folders (in /Theory) for:

/Algorithms
[Topological Sorting]
[DAGger Hashimoto]
[Create DAGger Hashimoto]
[Dijkstra] (this is something optional / personal: I would like to review  Dijkstra on Topological Sorting) 
[ETHASH]
[RSA]

This is one is very basic but will support the idea of the dev / doc - website:
/Tries
[Merkle Patricia Trie]
[Patricia Trie]
[Radix Trie]

Let me know what do you want in or out so I can begin to write it, so I can move forward on to coding or "pratical examples".

Question: Do you have a specific/defined writing style or should I just follow what is written as a model (just to be sured).

### CODE REVIEW

**Comment by JEAlfonsoP** [comment]
According to our latest conversation, this would be the proposal for the repo additions (/Theory/):

/Algorithms
[DAGger Hashimoto]
[Create DAGger Hashimoto]
[Dijkstra] (this is something optional / personal: I would like to review Dijkstra on Topological Sorting)
[ETHASH]
[RSA]

/Tries
[Merkle Patricia Trie]
[Patricia Trie]
[Radix Trie]

Please let me know if this is Ok. Ty.

**Comment by kevaundray** [comment]
Hi, 

Apologise if I was not clear, I think the algorithms section is nice to have though the table of topics, do not seem relevant to verkle tries. They do seem relevant to Ethereum as a whole though!

```
[DAGger Hashimoto]
[Create DAGger Hashimoto]
[Dijkstra] (this is something optional / personal: I would like to review Dijkstra on Topological Sorting)
[ETHASH]
[RSA]
```

Verkle trees do not use RSA and have nothing to do with Ethash for example.

The section on tries can be added, though we probably don't want to go into too much detail on the current MPT as verkle tries are a new construction with a lot of complexity already. Hmm but it may be nice to bridge the gap between the two.

**Comment by JEAlfonsoP** [comment]
No Problem, my mistake !

We will go with the /math section and with the section of /tries (not too much detail on it).

Correct ?

**Comment by kevaundray** [comment]
Yep that sounds good!

**Comment by kevaundray** [comment]
Thinking about it, this structure is strictly superior to what I had thought of before

**Pull request merged**
