### PR TITLE
Migrate Website to Docusaurus 

### PR DESCRIPTION
**Pull request by ControlCplusControlV**
I moved the Website to Docusaurus, right now it's still very much templately, but all the markdown files are moved and now work just has to be done on writing more docs and improving the landing page.

### CODE REVIEW

**Comment by ControlCplusControlV** [comment]
@kevaundray for review

**Comment by ControlCplusControlV** [comment]
*I also added plugins so we have KateX support

**Comment by ControlCplusControlV** [comment]
@kevaundray I know you have likely been busy (myself as well), but I was just wondering if you just needed more time to review or if there is something blocking on my end I missed?

**Comment by kevaundray** [comment]
> @kevaundray I know you have likely been busy (myself as well), but I was just wondering if you just needed more time to review or if there is something blocking on my end I missed?

Hi,

Yeah sorry I need more time to review this, some personal items came up and I had to prioritise finishing up other tasks.

I'll get to this as soon as I can. If I see anything that needs changing, I'll modify and push, so you don't need to come back and do a backwards and forwards.

**Comment by kevaundray** [comment]
Hmm my github is being weird, I'll merge this branch into master: https://github.com/ethereum/verkle-dev-website/tree/ControlCplusControlV/master

instead of trying to merge it into yours

**Pull request merged**
